In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('IMDB_Data.csv')
df.drop('Unnamed: 0',axis=1,inplace=True)

In [4]:
df.drop_duplicates(subset=['Movie_Name'],inplace=True)

In [5]:
df.reset_index(inplace=True,drop = True)
df.to_csv('IMDB_Data_without_duplicates.csv',index = False)

In [6]:
df.drop(['Movie_Metascore','Movie_Gross','Movie_Name','Movie_Date_Of_Release',
         'Movie_Rate','Movie_Length','Movie_Votes','Movie_Restriction'],axis=1,inplace=True)

In [7]:
genres = ['Action', 'Sci-Fi', 'Comedy', 'Crime', 'Western','Family',
          'Drama', 'Horror', 'Romance', 'Thriller','Adventure']

In [8]:
ser = df['Movie_Genres'].apply(lambda row : np.isin(genres, row.split(", ")).astype(int))

In [9]:
res = pd.DataFrame(ser.to_list(), columns=genres)

In [10]:
result = pd.concat([df.drop(['Movie_Genres'],axis = 1),res],axis =1)
result.to_csv('Movie_Description_and_Labels.csv', index = False)

In [11]:
result

,Movie_Description,Action,Sci-Fi,Comedy,Crime,Western,Family,Drama,Horror,Romance,Thriller,Adventure
0,When the menace known as the Joker wreaks havo...,1,0,0,1,0,0,1,0,0,0,0
1,Gandalf and Aragorn lead the World of Men agai...,1,0,0,0,0,0,1,0,0,0,1
2,A thief who steals corporate secrets through t...,1,1,0,0,0,0,0,0,0,0,1
3,While Frodo and Sam edge closer to Mordor with...,1,0,0,0,0,0,1,0,0,0,1
4,A meek Hobbit from the Shire and eight compani...,1,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5631,"A woman, separated from her unfaithful husband...",0,0,0,0,0,0,0,0,0,1,0
5632,A mysterious stranger with a harmonica joins f...,0,0,0,0,1,0,0,0,0,0,0
5633,Two bounty hunters with the same intentions te...,0,0,0,0,1,0,0,0,0,0,0
5634,A small-town sheriff in the American West enli...,0,0,0,0,1,0,0,0,0,0,0
5635,Missouri farmer Josey Wales joins a Confederat...,0,0,0,0,1,0,0,0,0,0,0

,Movie_Name,Movie_Description,Movie_Date_Of_Release,Movie_Genres,Movie_Rate,Movie_Length,Movie_Votes,Movie_Restriction,Action,Adventure,Biography,Comedy,Crime,Drama,Fantasy,Horror,Mystery,Romance,Thriller
0,The Dark Knight,When the menace known as the Joker wreaks havo...,2008,"Action, Crime, Drama",9.0,152,2580403,PG-13,1,0,0,0,1,1,0,0,0,0,0
1,The Lord of the Rings: The Return of the King,Gandalf and Aragorn lead the World of Men agai...,2003,"Action, Adventure, Drama",9.0,201,1790723,PG-13,1,1,0,0,0,1,0,0,0,0,0
2,Inception,A thief who steals corporate secrets through t...,2010,"Action, Adventure, Sci-Fi",8.8,148,2288875,PG-13,1,1,0,0,0,0,0,0,0,0,0
3,The Lord of the Rings: The Two Towers,While Frodo and Sam edge closer to Mordor with...,2002,"Action, Adventure, Drama",8.8,179,1617203,PG-13,1,1,0,0,0,1,0,0,0,0,0
4,The Lord of the Rings: The Fellowship of the Ring,A meek Hobbit from the Shire and eight compani...,2001,"Action, Adventure, Drama",8.8,178,1811783,PG-13,1,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5573,The Boy Next Door,"A woman, separated from her unfaithful husband...",2015,Thriller,4.7,91,41964,R,0,0,0,0,0,0,0,0,0,0,1
5574,Once Upon a Time in the West,A mysterious stranger with a harmonica joins f...,1968,Western,8.5,165,325043,PG-13,0,0,0,0,0,0,0,0,0,0,0
5575,For a Few Dollars More,Two bounty hunters with the same intentions te...,1965,Western,8.2,132,253085,R,0,0,0,0,0,0,0,0,0,0,0
5576,Rio Bravo,A small-town sheriff in the American West enli...,1959,Western,8.0,141,62051,Passed,0,0,0,0,0,0,0,0,0,0,0
5577,The Outlaw Josey Wales,Missouri farmer Josey Wales joins a Confederat...,1976,Western,7.8,135,73013,PG,0,0,0,0,0,0,0,0,0,0,0